Repository Romsou/Devops-project, pull requests merged in 2021-04, with the labels that each got.

#26 Add method to create DataFrame from arraylist of Line/column index
  src/main/java/dataframe/DataFrame.java
  src/test/java/dataframe/DataFrameTest.java
Labels: enhancement

#27 Test for Serie.print()
  src/test/java/dataframe/SerialTest.java
Labels: test

#28 Column name for Serie
  src/main/java/dataframe/Serie.java
Labels: enhancement

#29 Create codecov.yml
  .github/workflows/codecov.yml
  pom.xml
  src/main/java/dataframe/Serie.java
Labels: documentation

#31 Fix Serie/Serial
  src/main/java/dataframe/Serial.java
  src/main/java/dataframe/Serie.java
  src/test/java/dataframe/SerialTest.java
Labels: fix

#30 Column name DataFrame
  src/main/java/CustomExceptions/ColumnNotFoundException.java
  src/main/java/dataframe/DataFrame.java
  src/main/java/dataframe/Serie.java
  src/test/java/dataframe/DataFrameTest.java
Labels: enhancement, fix

#32 Badges codecoverage
  .github/workflows/codecov.yml
Labels: fix

#33 Badges pull request
  README.md
Labels: enhancement

#36 cleanup code
  src/main/java/CustomExceptions/ColumnSizeMismatch.java
  src/main/java/Main.java
  src/main/java/dataframe/DataFrame.java
  src/main/java/dataframe/Frame.java
  src/main/java/dataframe/Serial.java
  src/main/java/dataframe/Serie.java
  src/test/java/dataframe/DataFrameTest.java
Labels: documentation, fix

#37 Readme update
  README.md
Labels: documentation

#39 Added mean
  src/main/java/dataframe/Serial.java
  src/main/java/dataframe/Serie.java
Labels: documentation, enhancement

#40 add selection from min value
  src/main/java/dataframe/DataFrame.java
  src/test/java/dataframe/DataFrameTest.java
Labels: enhancement

#42 Badges codecoverage
  .github/workflows/codecov.yml
Labels: fix

#47 Deletion of _config.yml
  _config.yml
Labels: fix

#48 Updated readme with website
  README.md
Labels: documentation

#49 Update codecov.yml
  .github/workflows/codecov.yml
Labels: fix

#50 test exception DataFrameFromMinValue
  src/test/java/dataframe/DataFrameTest.java
Labels: test

#60 Delete codecov.yml
  .github/workflows/codecov.yml
Labels: fix

#62 update of the readme
  README.md
Labels: documentation
